const AD_UNIT_WIDTH = 300;
const AD_UNIT_HEIGHT = 250;
const AD_UNIT_ID = "";
const ADSENSE_CLIENT_ID = "";
const GA_TRACKING_ID = "";

export {
  AD_UNIT_WIDTH,
  AD_UNIT_HEIGHT,
  AD_UNIT_ID,
  ADSENSE_CLIENT_ID,
  GA_TRACKING_ID,
};
